---
title: "Flex Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}

library(flexdashboard)
library(tidyverse)
library(viridis)
library(rnoaa)
library(plotly)
library(lubridate)

stations <- ghcnd_stations()

stations %>% 
  filter(state == "NY", name == "BUFFALO") %>% 
  group_by(id) %>% 
  summarise(ly = max(last_year),
            min = min(first_year))

stations %>% 
  filter(state == "NY", str_detect(name, "ALBANY")) %>% 
  group_by(id) %>% 
  summarise(ly = max(last_year),
            min = min(first_year))

#central park id is USW00094728

nystationids <- c("USW00014733", "USW00014735", "USW00094728")

nydat <- meteo_pull_monitors(nystationids, 
                             date_min = "2018-01-01", 
                             date_max = "2018-12-31", 
                             var = c("PRCP", "SNOW", "SNWD", "TMAX", "TMIN")) %>% 
  mutate(name = recode(id, USW00014733 = "Buffalo_NY",
                       USW00014735 = "Albany_NY",
                       USW00094728 = "CentralPark_NY"),
         tmin = tmin / 10,
         tmax = tmax / 10,
         prcp = prcp / 10) %>%
  select(name, id, everything())

```

Column {data-width=650}
-----------------------------------------------------------------------

### Min and Max Temperature Relationship

```{r}

nydat %>% 
  mutate(text_label = str_c("Date: ", date)) %>%
  plot_ly(
    x = ~tmin, y = ~tmax, type = "scatter", mode = "markers",
    color = ~name, text = ~text_label, alpha = 0.4, size = 6)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Snowfall during Winter

```{r}

alb <- nydat %>% 
  filter(name == "Albany_NY",
         date <= as.Date("2018-04-20")) %>% 
  select(snow) %>% 
  rename("Albany_NY" = snow)
buf <- nydat %>% 
  filter(name == "Buffalo_NY",
         date <= as.Date("2018-04-20")) %>% 
  select(snow) %>% 
  rename("Buffalo_NY" = snow)
nyc <- nydat %>% 
  filter(name == "CentralPark_NY",
         date <= as.Date("2018-04-20")) %>% 
  select(snow) %>% 
  rename("CentralPark_NY" = snow)
x <- nydat %>% 
  select(date) %>% 
  distinct() %>% 
  filter(date <= as.Date("2018-04-20"))

d <-  cbind(x, alb, buf, nyc)

y <- list(
  title = "Snowfall amount (mm)"
)

plot_ly(d, x = ~date, y = ~Albany_NY, name = 'Albany_NY', type = 'scatter', mode = 'lines') %>%
  add_trace(y = ~Buffalo_NY, name = 'Buffalo_NY', mode = 'lines') %>%
  add_trace(y = ~CentralPark_NY, name = 'CentralPark_NY', mode = 'lines') %>% 
  layout(yaxis = y)

```

### Rainfall

```{r}

y <- list(
  title = "Log Transformed Precip. amount (mm)"
)

nydat %>% 
  na.omit() %>% 
  plot_ly(y = ~log(prcp), color = ~name, type = "box") %>% 
  layout(yaxis = y)

```

