---
title: "Plotly"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r}

library(tidyverse)
library(viridis)
library(rnoaa)
library(plotly)

```

```{r}

stations <- ghcnd_stations()

stations %>% 
  filter(state == "NY", name == "BUFFALO") %>% 
  group_by(id) %>% 
  summarise(ly = max(last_year),
            min = min(first_year))

stations %>% 
  filter(state == "NY", str_detect(name, "ALBANY")) %>% 
  group_by(id) %>% 
  summarise(ly = max(last_year),
            min = min(first_year))

#central park id is USW00094728

nystationids <- c("USW00014733", "USW00014735", "USW00094728")

nydat <- meteo_pull_monitors(nystationids, 
                             date_min = "2018-01-01", 
                             date_max = "2018-12-31", 
                             var = c("PRCP", "SNOW", "SNWD", "TMAX", "TMIN")) %>% 
  mutate(name = recode(id, USW00014733 = "Buffalo_NY",
                       USW00014735 = "Albany_NY",
                       USW00094728 = "CentralPark_NY"),
         tmin = tmin / 10,
         tmax = tmax / 10) %>%
  select(name, id, everything())

```


```{r}

nydat %>% 
  na.omit() %>% 
  plot_ly(y = ~prcp, color = ~name, type = "box")

```


```{r}

nydat %>% 
  plot_ly(x = ~name, y = ~snow, color = ~name, type = "bar")


# nydat %>% plotly(x = date, 
#                  y = prcp, 
#                  type = 'scatter', 
#                  mode = 'markers', 
#                  color = ~name)
# 
# Albany_NY <- nydat %>% filter(name == "Albany_NY") %>% select(prcp)
# Buffalo_NY <- nydat %>% filter(name == "Buffalo_NY") %>% select(prcp)
# CentralPark_NY <- nydat %>% filter(name == "CentralPark_NY") %>% select(prcp)
# x <- nydat %>% select(date) %>% distinct()
# data <- data.frame(x, Albany_NY, Buffalo_NY, CentralPark_NY)
# 
# plot_ly(data, x = ~x, y = ~Albany_NY, name = 'Albany_NY', type = 'scatter', mode = 'lines') %>%
#   add_trace(y = ~Buffalo_NY, name = 'Buffalo_NY', mode = 'lines') %>%
#   add_trace(y = ~CentralPark_NY, name = 'CentralPark_NY', mode = 'lines')

```


```{r}
nydat %>% 
  mutate(text_label = str_c("Date: ", date)) %>%
  plot_ly(
    x = ~tmin, y = ~tmax, type = "scatter", mode = "markers",
    color = ~name, text = ~text_label, alpha = 0.4, size = 6)

```